name: PyLint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pylint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/obyflow-python
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          persist-credentials: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"
      - run: pip install -e ".[dev]"
      - run: pip install pylint
      - run: pylint --fail-under=9.5 $(git ls-files '*.py')
